version: '3.8'
 
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dagster
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dagster_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  dagster:
    build: .
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: dagster
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dagster_password}
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_HOST: postgres
    env_file:
      - .env
    volumes:
      - .:/opt/dagster/code
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - postgres
 
volumes:
  postgres_data:
  dagster_home:
